// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW7TKIbv9MV7CRmol2P9JsZf08XOM9rko',
    appId: '1:73753882132:web:ac27f7c5cc729049218101',
    messagingSenderId: '73753882132',
    projectId: 'mobprog-perpusku',
    authDomain: 'mobprog-perpusku.firebaseapp.com',
    storageBucket: 'mobprog-perpusku.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCysEDB_6EDqfe7okgxdgyLtgDC5dc5KKE',
    appId: '1:73753882132:android:cff873fe2b66dab1218101',
    messagingSenderId: '73753882132',
    projectId: 'mobprog-perpusku',
    storageBucket: 'mobprog-perpusku.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnJio--zVdeIfelhGgmfJHTL2cbqy82HY',
    appId: '1:73753882132:ios:38530765f191f50d218101',
    messagingSenderId: '73753882132',
    projectId: 'mobprog-perpusku',
    storageBucket: 'mobprog-perpusku.appspot.com',
    iosClientId: '73753882132-50suhi1cfrir4tnj03l6k0rr69aef4ps.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobprogPerpusku',
  );
}
